apiVersion: apps/v1
kind: Deployment
metadata:
  name: shreynode-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shreynode
  template:
    metadata:
      labels:
        app: shreynode
    spec:
      containers:
        - name: shreynode-container
          image: shrey209/shreynode1:1744363093
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_URI
