apiVersion: v1
kind: Service
metadata:
  name: shreynode-loadbalancer
spec:
  selector:
    app: shreynode
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 80 # Port inside the container
  type: LoadBalancer
